// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	storage.proto

It has these top-level messages:
	File
	Response
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type File struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Size    int64  `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Type    string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Content []byte `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *File) Reset()                    { *m = File{} }
func (m *File) String() string            { return proto1.CompactTextString(m) }
func (*File) ProtoMessage()               {}
func (*File) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *File) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type Response struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto1.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto1.RegisterType((*File)(nil), "proto.File")
	proto1.RegisterType((*Response)(nil), "proto.Response")
}

func init() { proto1.RegisterFile("storage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x2e, 0xc9, 0x2f,
	0x4a, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x31, 0x5c,
	0x2c, 0x6e, 0x99, 0x39, 0xa9, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0x60, 0x36, 0x48, 0xac, 0x38, 0xb3, 0x2a, 0x55, 0x82, 0x49, 0x81, 0x51,
	0x83, 0x39, 0x08, 0xcc, 0x06, 0x89, 0x95, 0x54, 0x16, 0xa4, 0x4a, 0x30, 0x43, 0xd4, 0x81, 0xd8,
	0x42, 0x12, 0x5c, 0xec, 0xc9, 0xf9, 0x79, 0x25, 0xa9, 0x79, 0x25, 0x12, 0x2c, 0x0a, 0x8c, 0x1a,
	0x3c, 0x41, 0x30, 0xae, 0x92, 0x0c, 0x17, 0x47, 0x50, 0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa,
	0x90, 0x00, 0x17, 0x73, 0x6e, 0x71, 0x3a, 0xd4, 0x02, 0x10, 0xd3, 0xc8, 0x90, 0x8b, 0x3d, 0x18,
	0xe2, 0x26, 0x21, 0x35, 0x2e, 0x96, 0xe0, 0xc4, 0xb2, 0x54, 0x21, 0x6e, 0x88, 0xeb, 0xf4, 0x40,
	0x6e, 0x92, 0xe2, 0x87, 0x72, 0x60, 0x46, 0x28, 0x31, 0x24, 0xb1, 0x81, 0x45, 0x8c, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x22, 0x7e, 0x98, 0xe5, 0xcd, 0x00, 0x00, 0x00,
}
